name: Scan with Detekt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
     - cron: '20 21 * * 3'
  workflow_dispatch:

env:
  DETEKT_URL: https://github.com/detekt/detekt/releases/download/v1.23.1/detekt-cli-1.23.1-all.jar

jobs:
  analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # For uploading results

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Detekt
      run: |
        dest=$( mktemp -d )
        curl --request GET --url $DETEKT_URL --location --output $dest/detekt
        java -jar $dest/detekt --input ${{ github.workspace }} --base-path ${{ github.workspace }} --report sarif:${{ github.workspace }}/detekt.sarif.json
    - name: Upload
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ github.workspace }}/detekt.sarif.json
        checkout_path: ${{ github.workspace }}
