name: Scan with Detekt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 21 * * 3'
  workflow_dispatch:

env:
  DETEKT_URL: https://github.com/detekt/detekt/releases/download/v1.23.1/detekt-cli-1.23.1-all.jar

jobs:
  analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    permissions:
      security-events: write # For uploading results

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'
          cache: 'gradle'
      - name: Run Detekt
        continue-on-error: true
        run: ./gradlew detekt
      - name: Upload
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/reports/detekt/detekt.sarif
